2022-09-30 05:46:07.330 | DEBUG    | hcaptcha_challenger._solutions.kernel:_request_asset:299 - Downloading objects.yaml from https://raw.githubusercontent.com/QIN2DIM/hcaptcha-challenger/main/src/objects.yaml
2022-09-30 05:46:07.382 | DEBUG    | hcaptcha_challenger._solutions.kernel:request_assets:132 - Pulling AssetsObject from https://api.github.com/repos/qin2dim/hcaptcha-challenger/releases
2022-09-30 05:46:07.513 | DEBUG    | hcaptcha_challenger._solutions.kernel:_request_asset:299 - Downloading yolov6n.onnx from https://github.com/QIN2DIM/hcaptcha-challenger/releases/download/model/yolov6n.onnx
2022-09-30 05:46:08.824 | INFO     | services.deploy:job_loop_claim:125 - >> STARTUP [AwesomeScheduler] SynergyTunnel Pattern: True
2022-09-30 05:46:08.876 | DEBUG    | services.bricklayer.core:load_ctx_cookies:1201 - >> LOAD [CookieManager] Load context cookie.
2022-09-30 05:46:09.238 | SUCCESS  | services.bricklayer.core:refresh_ctx_cookies:1268 - >> MATCH [__Context__] üéÆ ÂêØÂä®ÊåëÊàòËÄÖ‰∏ä‰∏ãÊñá - ctx_session=False
2022-09-30 05:46:09.802 | INFO     | services.utils.toolbox:get_challenge_ctx:179 - Please use `xvfb` to empower the headful Chrome.
2022-09-30 05:46:09.802 | INFO     | services.utils.toolbox:get_challenge_ctx:180 - CMD: xvfb-run python3 main.py claim
2022-09-30 05:47:10.372 | ERROR    | services.deploy:__enter__:192 - Message: unknown error: cannot connect to chrome at 127.0.0.1:33937
from chrome not reachable
Stacktrace:
#0 0x55a46a11d693 <unknown>
#1 0x55a469f169db <unknown>
#2 0x55a469f0681e <unknown>
#3 0x55a469f3f677 <unknown>
#4 0x55a469f36e9f <unknown>
#5 0x55a469f72953 <unknown>
#6 0x55a469f6c743 <unknown>
#7 0x55a469f42533 <unknown>
#8 0x55a469f43715 <unknown>
#9 0x55a46a16d7bd <unknown>
#10 0x55a46a170bf9 <unknown>
#11 0x55a46a152f2e <unknown>
#12 0x55a46a1719b3 <unknown>
#13 0x55a46a146e4f <unknown>
#14 0x55a46a190ea8 <unknown>
#15 0x55a46a191052 <unknown>
#16 0x55a46a1ab71f <unknown>
#17 0x7fcf6e0cb609 <unknown>

Traceback (most recent call last):
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/services/scaffold.py", line 133, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/services/deploy.py", line 132, in job_loop_claim
    with GameClaimerInstance(self.silence, log_ignore=log_ignore) as claimer:
> File "/home/runner/work/game_auto_get/game_auto_get/epic/src/services/deploy.py", line 184, in __enter__
    if _manager.refresh_ctx_cookies(keep_live=True, silence=self.silence):
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/services/bricklayer/core.py", line 1277, in refresh_ctx_cookies
    ctx = ctx_session or get_challenge_ctx(silence=silence)
  File "/home/runner/work/game_auto_get/game_auto_get/epic/src/services/utils/toolbox.py", line 183, in get_challenge_ctx
    return Challenger(options=options, driver_executable_path=driver_wrapper.path)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33937
from chrome not reachable
Stacktrace:
#0 0x55a46a11d693 <unknown>
#1 0x55a469f169db <unknown>
#2 0x55a469f0681e <unknown>
#3 0x55a469f3f677 <unknown>
#4 0x55a469f36e9f <unknown>
#5 0x55a469f72953 <unknown>
#6 0x55a469f6c743 <unknown>
#7 0x55a469f42533 <unknown>
#8 0x55a469f43715 <unknown>
#9 0x55a46a16d7bd <unknown>
#10 0x55a46a170bf9 <unknown>
#11 0x55a46a152f2e <unknown>
#12 0x55a46a1719b3 <unknown>
#13 0x55a46a146e4f <unknown>
#14 0x55a46a190ea8 <unknown>
#15 0x55a46a191052 <unknown>
#16 0x55a46a1ab71f <unknown>
#17 0x7fcf6e0cb609 <unknown>

2022-09-30 05:47:10.379 | ERROR    | services.deploy:_bad_omen:260 - >> Notify [GameClaimer] Êé®ÈÄÅËøêË°åÊó•Âøó - active_pusher=[] err=Message: unknown error: cannot connect to chrome at 127.0.0.1:33937
from chrome not reachable
Stacktrace:
#0 0x55a46a11d693 <unknown>
#1 0x55a469f169db <unknown>
#2 0x55a469f0681e <unknown>
#3 0x55a469f3f677 <unknown>
#4 0x55a469f36e9f <unknown>
#5 0x55a469f72953 <unknown>
#6 0x55a469f6c743 <unknown>
#7 0x55a469f42533 <unknown>
#8 0x55a469f43715 <unknown>
#9 0x55a46a16d7bd <unknown>
#10 0x55a46a170bf9 <unknown>
#11 0x55a46a152f2e <unknown>
#12 0x55a46a1719b3 <unknown>
#13 0x55a46a146e4f <unknown>
#14 0x55a46a190ea8 <unknown>
#15 0x55a46a191052 <unknown>
#16 0x55a46a1ab71f <unknown>
#17 0x7fcf6e0cb609 <unknown>

